*** Variables ***
# Static Variables
${Chrome_BROWSER}           Chrome
${google_URL}               https://www.google.com/
${google_title}             Google
${Cv1Hub_URL}               https://cv1-uat.3601.com.hk/hub/e-submission/

# Search Criteria
${robot_framework}          Robot Framework
${chrome_driver}            Chrome Driver
${selenium}                 Selenium
${appium}                   Appium
${github}                   Github

#Username & Password for CV1 UAT
${username}                 DD0001
${password}                 Convoy2345#